### ISSUE TITLE
nested foreach doesn't work

### ISSUE THREAD

**Issue by Strandedpirate** [mbest/knockout.punches#36]
If you swap the nested foreach below with a standard `<!-- ko foreach: licenses -->` it starts working.

        {{#foreach: products}}
            <div>{{productName}}
            {{#foreach: licenses}}
                <div>{{licenseGuid}}</div>
            {{/foreach}}
           </div>
        {{/foreach}}

**Comment by mbest** [comment]
There's just no way to fix this.
