### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by damiandennis** [mbest/knockout.punches#38]
Great work on this btw. Any chance we can get a bower config file?

**Comment by crissdev** [comment]
@mbest Any particular reason why `knockout` is not in the `dependencies`? I can't see how this library can be used without `knockout`. Apart from the dependency chain, it would save one `bower install` command.

**Comment by mbest** [comment]
@crissdev Feel free to submit the change.

**Comment by crissdev** [comment]
PR #48
