### ISSUE TITLE
'Default' filter does not evaluate properly for functions

### ISSUE THREAD

**Issue by robertmclaws** [mbest/knockout.punches#46]
**Expected behavior:**
When a function is specified for a binding, execute the function. If the value returned is null or an empty string, replace the value with the Default Value.

**Actual Behavior:**
When a function is specified for a binding, the function is returned and the Default Value is ignored.

**Comment by robertmclaws** [comment]
Ignore the above commit. I'm fixing it a different way.

**Comment by mbest** [comment]
This would mean that the default filter works differently from other filters. The only reason the function check is in the code now is so that functions don't get confused with arrays (since both have a `length`) property.
