### ISSUE TITLE
Punches foreach doesn't work outside tr

### ISSUE THREAD

**Issue by BMeyerKC** [mbest/knockout.punches#50]
I am trying to use punches in a similar way I would with normal ko syntax. But I found it doesn't like being outside of certain elements. I created a jsfiddle to explain better.

https://jsfiddle.net/bmeyerkc/q1oh0dzu/

It outputs the comment without the inner html wrapped.

**Comment by crissdev** [comment]
@BMeyerKC Most probably is due to the fact that `plain text` is not allowed in `tr` or `tbody`.

---

See `Permitted content` in `Usage context` section

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tbody
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tr

**Comment by mbest** [comment]
See #33

**Comment by crissdev** [comment]
@mbest I would follow the comment in #33 and add a small note in the documentation. Might save other people time.

> [...] Could be worth putting a one liner on your readme/website

Thanks.

**Comment by BMeyerKC** [comment]
Shouldn't there be someway of getting it to work?
