### ISSUE TITLE
Incompatible with Swig template engine for node.js?

### ISSUE THREAD

**Issue by alvarotrigo** [mbest/knockout.punches#54]
I'm using [Swig as a Javascript template engine](http://paularmstrong.github.io/swig/) for node.js which also uses the syntax `{{ variable }}` to print variables from the server side.

It seems there's a conflict using both. Any way to avoid it?

**Comment by mbest** [comment]
Since neither lets you define an alternate syntax, I'm not sure how you'd use them together.

**Comment by alvarotrigo** [comment]
Yeah right. Just to verify. Thanks.
