### ISSUE TITLE
Issue with setting 'disabled' property in IE8 with Punches syntax

### ISSUE THREAD

**Issue by webketje** [mbest/knockout.punches#55]
Given a property on an object:

```
this.locked = ko.pureComputed(function() { return this.data.access() === 'locked' }, this);
```

Bound to the view like this:

```
<button type="button" disabled="{{ locked }}"></button>
```

IE8 (compat mode) will return true in all cases and lock all inputs. This is not the case when using namespaced `attr.disabled` or KO `attr: { disabled:` bindings. Is there any way to remove the attribute altogether when the returned value is falsey? [It's in the spec](http://www.w3.org/TR/html5/infrastructure.html#boolean-attributes)

**Comment by mbest** [comment]
Okay. I'll check it out.

**Comment by webketje** [comment]
Haven't checked, but the same might apply to the `checked` attribute.

**Comment by mbest** [comment]
It appears that IE 8 replaces `disabled="{{ locked }}"` with `disabled="disabled"` while parsing, and therefore before Knockout Punches sees it.

**Comment by mbest** [comment]
The workaround is to use `disable="{{ locked }}"` which will bind to the built-in `disable` binding.

**Comment by mbest** [comment]
@webketje, You are right. IE 8 has the same problem with `checked`. Here's a workaround:

```
ko.bindingHandlers.check = ko.bindingHandlers.checked;
```

```
<input type="checkbox" name="name" check="{{ isChecked }}"/>
```

**Comment by mbest** [comment]
Perhaps one way Punches can help work around this issue is to support alternate attribute names such as `data-checked` or `ko-checked`.

**Comment by webketje** [comment]
@mbest  I didn't know that Punches enabled binding names as custom attributes, I'd only used the standard HTML ones, so thanks. Guess nothing else can be done but a documentation footnote (if it is worth that)..

**Comment by IanYates** [comment]
I didn't realise you could use custom attributes in this manner either.  Good to know :)

**Comment by webketje** [comment]
IE8 support no longer relevant
