### ISSUE TITLE
Filters with custom bindings

### ISSUE THREAD

**Issue by alexswan10k** [mbest/knockout.punches#59]
So I know I can do:

```
<span data-bind="text: name | fit:20 | uppercase"></span>
```

but what I really want to do is:

```
<div data-bind="someCustomBinding: data | transform | transform2:param"></div>
```

where data is an array of a known thing, or other complex object. It looks like currently the punches syntax is only supported for text and css.

Is this possible?

**Comment by mbest** [comment]
As described in the [documentation](http://mbest.github.io/knockout.punches/#text-filters), you'd use `ko.punches.textFilter.enableForBinding('someCustomBinding')` or `ko.punches.textFilter.enableForBinding(ko.bindingHandlers.someCustomBinding)`.

**Comment by alexswan10k** [comment]
Thanks, I went over this a few times and it didn't occur to me it was what i wanted. Apologies. I think I dismissed it because applying a function off a binding that is totally unrelated to the binding I wished to target seemed counter intuitive.

**Comment by mbest** [comment]
Are you saying that the documentation is confusing or the API? Can you elaborate?

**Comment by alexswan10k** [comment]
The API.

I am using
`ko.bindings.someCustomBinding` with the filter `ko.punches.someCustomFilter`, and it seems a little odd that i would have to go through `ko.punches.textFilter` (totally unrelated filter) to hook this binding up. 

I understand there are perhaps implementation reasons for this, but I guess I would have expected something closer to `ko.punches.enableForBinding(binding)`?

**Comment by mbest** [comment]
Thanks for the extra details. I'll see if I can make the documentation more clear.

**Comment by alexswan10k** [comment]
Much appreciated. Thanks.
