### ISSUE TITLE
Dynamic binding problem when using html binding

### ISSUE THREAD

**Issue by oguzhaneren** [mbest/knockout.punches#60]
Hi,

When I write {{something}} to textarea, knockout try to apply binding then it causing error.

{{something}} is not binding expression, it just a text from user input.

How can I prevent this dynamic binding?

``` html
<textarea data-bind="value:code"></textarea>

Preview:
<div data-bind="html:code">

</div>
```

**Comment by mbest** [comment]
Which versions of Punches and Knockout are you using?

**Comment by oguzhaneren** [comment]
ko version: 3.4.0
ko.punches version: 0.5.1

this is the case: http://codepen.io/anon/pen/NxvoqW

**Comment by jlaustill** [comment]
I have actually ran into this as well trying to make an example page.  Is there a way to escape a block of text so it doesn't get processed by ko.punches.  I've dug through the code quite a bit at this point and I'm not really sure how ko parses the dom, or if there's a binding that lets knockout pass each element to punches.  I'll dig through that today and see if I can't figure it out.

**Comment by mbest** [comment]
The problem isn't in the `<textarea>`, but in the `markdown` binding. Your binding needs to tell Knockout not to parse its descendants (copied from the `html` binding):

```
init: function() {
    // Prevent binding on the dynamically-injected HTML (as developers are unlikely to expect that, and it has security implications)
    return { controlsDescendantBindings: true };
},
```

http://codepen.io/anon/pen/gPxNdW
