### ISSUE TITLE
$data within handle bars? - Cannot apply bindings multiple times to the same element

### ISSUE THREAD

**Issue by tom-pb** [mbest/knockout.punches#69]
I've encountered an issue binding data within a nested foreach block using {{$data}}. The following error appears:

"cannot apply bindings multiple times to the same element"

I've created a fiddle to replicate: https://jsfiddle.net/usmgLjhc/

I can work around the issue by replacing {{$data}} with a span (e.g. data-bind="text: $data"),

or by wrapping {{$data}} within another div so that it's not the immediate child of the ko foreach comment block... but I'm guessing there's some issue here.

I like the handle-bar syntax as it's much cleaner. Should it be possible to use $data within handle-bars when it's the immediate child within a foreach?

**Comment by mbest** [comment]
This appears to be a bug in Knockout. Specifically, after calling `callbackAfterAddingNodes`, `lastNode` is not valid in this case, which causes the elements for the next item to be inserted in the wrong location.

**Comment by tom-pb** [comment]
Thanks @mbest  for the quick reply and the diagnosis. It looks like I had incorrectly assumed that it was an issue with punches as opposed to KO itself...

I've actually just encountered another issue and wonder if it is related or different. I've trimmed my code down into a fiddle that replicates it.

https://jsfiddle.net/L3fdoqz4/

This time the problem occurs using the `{{#foreach: xxx}}` syntax in a nested scenario. I can fix/avoid the issue by changing the nested foreach to the classic KO comment syntax: `<!-- ko foreach: xxx -->`.

Would you say this is the same issue?

**Comment by mbest** [comment]
> Would you say this is the same issue?

No, it's a different issue. Because Knockout and Punches process the template after it's been parsed by the browser, it must still obey the browser's rules. Browsers don't allow text inside the `<tbody>` element and so move it somewhere else, in this case outside the `<table>` itself.

**Comment by tom-pb** [comment]
Ah yes, that makes sense.

So with that cleared up, coupled with the fact that my original issue doesn't relate to Punches, I'll close it here and report the bug over in the KO repo. Thanks for your assistance @mbest.
